### ISSUE TITLE
error on toggle map

### ISSUE THREAD

**Issue by deathcore01** [Rythal/Carbonite#143] opened 2014-12-25 14:22 UTC
if i toggle minimap (press M) i have this error:

54x FrameXML\WorldMapFrame.lua:1427: attempt to perform arithmetic on local 'centerY' (a nil value)
FrameXML\WorldMapFrame.lua:1427: in function <FrameXML\WorldMapFrame.lua:1416>

Locals:

i have found the problem in file NxMap.Lua, 

local ttl = 0
function Nx.Map.OnUpdate (this, elapsed)	--V4 this
	ttl = ttl + elapsed
	if ttl < .02 then
		return
	end
	ttl = 0

change to

--local ttl = 0
function Nx.Map.OnUpdate (this, elapsed)	--V4 this
--	ttl = ttl + elapsed
--	if ttl < .02 then
--		return
--	end
--	ttl = 0

will eliminate this error.

cu DeaTHCorE

**Comment by SenorKarlos** [comment] 2015-01-01 02:28
Heres the full error I get, Happy New Years!! :)

Date: 2014-12-31 21:26:56
ID: 1
Error occured in: Global
Count: 1
Message: ..\FrameXML\WorldMapFrame.lua line 1427:
   attempt to perform arithmetic on local 'centerY' (a nil value)
Debug:
   ..\FrameXML\WorldMapFrame.lua:1427:
      ..\FrameXML\WorldMapFrame.lua:1416
Locals:
self = WorldMapButton {
 0 = <userdata>
 OutlandHighlight = <unnamed> {
 }
 AzerothHighlight = <unnamed> {
 }
 DraenorHighlight = <unnamed> {
 }
}
elapsed = 0.013000000268221
x = 1419.1590815016
y = 409.60004695012
centerX = nil
centerY = nil
width = 1002.0000610352
height = 668
(*temporary) = 334
(*temporary) = 668
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'centerY' (a nil value)"
BLIP_TEX_COORDS = <table> {
 HUNTER = <table> {
 }
 WARRIOR = <table> {
 }
 PALADIN = <table> {
 }
 MAGE = <table> {
 }
 PRIEST = <table> {
 }
 WARLOCK = <table> {
 }
 DEATHKNIGHT = <table> {
 }
 SHAMAN = <table> {
 }
 DRUID = <table> {
 }
 MONK = <table> {
 }
 ROGUE = <table> {
 }
}
BLIP_RAID_Y_OFFSET = 0.5

AddOns:
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  WowheadLooter, v60005
  Ace3, v
  Altoholic, vr151
  Archy, v1.8.56
  AskMrRobot, v19
  AucAdvanced, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21c.5521.5459(5.21c/embedded)
  AucMatchUndercut, v5.21c.5521.5507(5.21c/embedded)
  AucStatHistogram, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatSales, v5.21c.5521.5476(5.21c/embedded)
  AucStatSimple, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21c.5521.5323(5.21c/embedded)
  AucUtilAHWindowControl, v5.21c.5521.5347(5.21c/embedded)
  AucUtilAppraiser, v5.21c.5521.5495(5.21c/embedded)
  AucUtilAskPrice, v5.21c.5521.5447(5.21c/embedded)
  AucUtilAutoMagic, v5.21c.5521.5443(5.21c/embedded)
  AucUtilCompactUI, v5.21c.5521.5496(5.21c/embedded)
  AucUtilEasyBuyout, v5.21c.5521.5507(5.21c/embedded)
  AucUtilFixAH, v5.21c.5521 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21c.5521.5417(5.21c/embedded)
  AucUtilPriceLevel, v5.21c.5521.5458(5.21c/embedded)
  AucUtilScanButton, v5.21c.5521.5403(5.21c/embedded)
  AucUtilScanFinish, v5.21c.5521.5515(5.21c/embedded)
  AucUtilScanProgress, v5.21c.5521.4979(5.21c/embedded)
  AucUtilScanStart, v5.21c.5521.5347(5.21c/embedded)
  AucUtilSearchUI, v5.21c.5521.5515(5.21c/embedded)
  AucUtilSimpleAuction, v5.21c.5521.5514(5.21c/embedded)
  AucUtilVendMarkup, v5.21c.5521.4828(5.21c/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v6.0.16
  Bagnon, v6.0.16
  Bartender4, v4.6.5
  BeanCounter, v5.21c.5521 (SanctimoniousSwamprat)
  BrokerEquipment, v60000.26-Release
  BrokerProfessions, v
  BrokerMounts, v6.03
  Carbonite, v6.0.1
  CarboniteInfo, v1.0
  CarboniteNotes, v1.1
  CarboniteQuests, v1.0
  CarboniteSocial, v1.0
  CarboniteWarehouse, v1.0
  CarboniteWeekly, v1.0
  Configator, v5.1.DEV.376(/embedded)
  DataStore, vr51
  DataStoreAchievements, vr38
  DataStoreAgenda, vr19
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr29
  DataStoreContainers, v6.0.002
  DataStoreCrafts, vr63
  DataStoreCurrencies, v6.0.002
  DataStoreGarrisons, vr6
  DataStoreInventory, vr40
  DataStoreMails, vr39
  DataStorePets, vr36
  DataStoreQuests, vr31
  DataStoreReputations, v6.0.002
  DataStoreSpells, v6.0.002
  DataStoreStats, v6.0.002
  DataStoreTalents, v6.0.002
  DBMCore, v
  DBMDefaultSkin, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v5.21c.5521 (SanctimoniousSwamprat)
  EnchantrixBarker, v5.21c.5521 (SanctimoniousSwamprat)
  Gatherer, v5.0.0
  Glamour, v1.4.4
  icebox, v0.1.1
  IceHUD, v1.9.7
  Informant, v5.21c.5521 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.363(/embedded)
  LibSharedMedia30, v3.0-89
  MogIt, v3.4.0
  MoveAnything, v15.0.7
  Omen, v3.1.9
  OmniCC, v6.0.10
  Overachiever, v0.81
  OverachieverTabs, v0.81
  Postal, v3.5.1
  Recount, vv6.0.3e release
  SlideBar, v5.21c.5521 (SanctimoniousSwamprat)
  Stubby, v5.21c.5521 (SanctimoniousSwamprat)
  TipHelper, v5.12.DEV.351(/embedded)
  Titan, v5.4.3.60000
  TitanBag, v5.4.3.60000
  TitanClock, v5.4.3.60000
  TitanCurrency, v6.0
  TitanGold, v5.4.3.60000
  TitanLocation, v5.4.3.60000
  TitanLogout, v1.3.0
  TitanLootType, v5.4.3.60000
  TitanPerformance, v5.4.3.60000
  TitanRepair, v5.4.3.60000
  TitanReputation, v3.8.6
  TitanSpec, v4.0
  TitanTrashCan, vv4.0.0
  TitanVolume, v5.4.3.60000
  TitanXP, v5.4.3.60000
  Viewporter, v
  WIM, v3.6.22
  WoWDBProfiler, v
  WowheadGarrisonTimer, v1.0.9
  XLoot, vz21a-release
  XLootFrame, vz21a-release
  XLootGroup, vz21a-release
  XLootMaster, vz21a-release
  XLootMonitor, vz21a-release
  BlizRuntimeLib_enUS v6.0.3.60000 <none>
  (ck=ef1)

**Comment by SenorKarlos** [comment] 2015-01-01 21:20
I'm using the latest Git and still getting this. I'm going to try and wipe all my addon settings(and curse backup lol.... that thing sometimes....) and start from scratch, a couple others need some tweaking too. I'll reply again in a while

**Comment by atk** [comment] 2015-01-01 22:27
That's because the fix is not merged yet before another developer has confirmed that it is OK.

**Comment by SenorKarlos** [comment] 2015-01-01 22:44
ohhhh hah still new to how Git works

**Comment by DiegoSnip** [comment] 2015-01-02 02:10
Hi, the problem seems to be solved.

I have this different one on Battle for Gineas BG, I don't know if it is related to this problem.

Error:

Message: Interface\AddOns\Carbonite\NxMap.lua:9059: attempt to perform arithmetic on field 'Y' (a nil value)
Time: 01/01/15 22:59:02
Count: 784
Stack: Interface\AddOns\Carbonite\NxMap.lua:9059: in function `GetWorldZoneInfo'
Interface\AddOns\Carbonite\NxMap.lua:4525: in function `Update'
Interface\AddOns\Carbonite\NxMap.lua:3815: in function <Interface\AddOns\Carbonite\NxMap.lua:3725>

Locals: self = <table> {
 InstMapWX2 = -1329.2593012695
 MiniBlks = 12
 IconScale = 3
 MenuIShowWorld = <table> {
 }
 GIconMenuITogInst = <table> {
 }
 PlyrRZY = 23.22553396225
 MMScalesC = <table> {
 }
 LOpts = <table> {
 }
 TextFStrs = <table> {
 }
 PlyrLastDir = 189.99025314283
 Scrolling = false
 Menu = <table> {
 }
 EffScale = 0.791752576828
 Zone = 736
 WorldAlpha = 0
 StartupShown = true
 ScaleDraw = 1.2088048524515
 BackgndAlphaFade = 0.4
 MoveLastX = 0
 PlyrDir = 189.99025314283
 PlyrSpeedCalcTime = 17925.475
 MapPosYDraw = 0
 PlyrSpeed = 0
 MapScale = 0.12063920683149
 CurMapBG = true
 PadX = 0
 BGIncNum = 0
 ViewSavedData = <table> {
 }
 MapW = 280.88006591797
 MMGathererUpdateDelay = 1
 LClickTime = 0
 MouseEnabled = true
 ButAutoScaleOn = <table> {
 }
 MapH = 265.00003051758
 MMScales = <table> {
 }
 WorldMapFrmScale = 1
 MapPosX = 0
 BackgndAlphaTarget = 0.4
 MapsDrawnOrder = <table> {
 }
 BGGrowBars = true
 ArrowScroll = 0.14
 H = 141
 Tick = 37210
 IconNIFrms = <table> {
 }
 LastDungeonLevel = 0
 BaseScale = 1
 ToolBar = <table> {
 }
 MoveLastY = 0
 MenuIShowHerb = <table> {
 }
 DotPartyScale = 1
 PlyrX = 0
 QuestAlpha = 0.3
 InstMapWX1 = -1333.1733637695
 CurWorldUpdateOverlayNum = 1
 Scale = 1.2088048524515
 Targets = <table> {
 }
 BackgndAlpha = 0.4
 ArrowPulse = 1
 MenuIShowMine = <table> {
 }
 MapId = 736
 MMOwn = false
 Size1 = 0.94726562558814
 ShowUnexplored = false
 InstLevelSet = 0
 Arch = <unnamed> {
 }
 PIconMenu = <table> {
 }
 InstMapWY1 = 1146.4532901611
 DotRaidScale = 1
 MapIndex = 1
 StepTime = 0
 PlyrSpeedX = 0
 PlyrFrm = <unnamed> {
 }
 DebugAdjustScale = 0.1
 TrackETA = false
 IconStaticFrms = <table> {
 }
 UpdateTrackingDelay = 0
 IconNavScale = 1.0000034026568
 WorldMapFrmParent = WorldMapDetailFrame {
 }
 MiniFrms = <table> {
 }
 InCombat = false
 TrackPlayer = "Shaoxiao"
 Win = <table> {
 }
 InstanceId = false
 RealScale = 1.2088048524515
 Data = <table> {
 }
 InstMapWY2 = 1149.0626651611
 TrackDir = false
 InstMapInfo = <table> {
 }
 BGIconMenu = <table> {
 }
 CurOverlays = false
 MMOwnedFrms = <table> {
 }
 TrackPlyrs = <table> {
 }
 WorldHotspotTipStr = "Kalimdor, Azshara (10-20)
"
 TextScFrm = <unnamed> {
 }
 WorldMapFrmMapId = 321
 GIconMenuIFindNote = <table> {
 }
 TextFrm = <unnamed> {
 }
 QuestWin = <unnamed> {
 }
 WorldHotspotsCity = <table> {
 }
 ScaleDrawW = 0.82726338992765
 ArchAlpha = 0.3
 TileFrms = <table> {
 }
 Tracking = <table> {
 }
 MapPosY = 0
 Guide = <table> {
 }
 WorldHotspots = <table> {
 }
 PlyrY = 0
 TargetNextUniqueId = 1
 Cont = 90
 TransMenu = <table> {
 }
 GIconMenu = <table> {
 }
 ContFrms = <table> {
 }
 Level = 16
 CurWorldUpdateMapId = 736
 ScaleW = 0.82726338992765
 BackgndAlphaFull = 1
 CurOpts = <table> {
 }
 MenuIPlyrFollow = <table> {
 }
 TitleH = 0
 LocTipFrm = NxMapTip {
 }
 IconFrms = <table> {
 }
 W = 150
 MenuIMonitorZone = <table> {
 }
 PlyrSpeedY = 0
 LocTipFStrs = <table> {
 }
 PlyrRZX = 59.178972244263
 KillShow = false
 MMChkDelay = 19
 NeedWorldUpdate = false
 MapPosXDraw = 0
 MoveDir = 180
 Frm = <unnamed> {
 }
 MapsDrawnFade = <table> {
 }
 UpdateTargetDelay = 0
 DotPalScale = 1
 DotZoneScale = 1.0000034026568
}
cont = 90
zone = 736
name = "The Battle for Gilneas"
info = <table> {
 Y = 200
 X = 2000
 Name = "BG"
}
winfo = <table> {
 X = 2000
 Name = "The Battle for Gilneas"
 Zone = 736
 Scale = 2.6041665649414
 Cont = 90
 Short = "TBG"
}
x = 4000
(*temporary) = 200
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field 'Y' (a nil value)"

**Comment by SenorKarlos** [comment] 2015-01-02 03:25
All fixed here too, thanks! Dunno about Gilneas, havent been yet

**Closed** 2015-01-02 06:39 UTC
Labels: bug, Main Addon
